#!/usr/bin/env node
const os = require("os");
const fs = require("fs/promises");
const path = require("path");
const { spawnSync } = require("child_process");

async function main() {
  const tmp = await fs.mkdtemp(path.join(os.tmpdir(), "goya-dict-"));
  spawnSync(
    "cargo",
    [
      "run",
      "-p",
      "goya-cli",
      "--release",
      "--",
      "--dicdir",
      tmp,
      "compile",
      process.argv[2],
    ],
    { stdio: "inherit" }
  );

  const base = path.join(__dirname, "..");
  const generatedDir = path.join(base, "wasm-core", "__generated__");
  const pkgDir = path.join(base, "wasm-core", "pkg");
  await Promise.all([fs.mkdir(generatedDir), fs.mkdir(pkgDir)]);
  await Promise.all([
    fs.rename(path.join(tmp, "da.bin"), path.join(generatedDir, "da.bin")),
    fs.rename(path.join(tmp, "dict.bin"), path.join(generatedDir, "dict.bin")),
    fs.rename(
      path.join(tmp, "features.json"),
      path.join(pkgDir, "features.json")
    ),
  ]);
}

main();
