#!/usr/bin/env node
const os = require("os");
const fs = require("fs/promises");
const path = require("path");
const { spawnSync } = require("child_process");

async function main() {
  const tmp = await fs.mkdtemp(path.join(os.tmpdir(), "goya-dict-"));
  spawnSync(
    "cargo",
    [
      "+nightly",
      "run",
      "-p",
      "goya-cli",
      "--release",
      "--",
      "--dicdir",
      tmp,
      "compile",
      process.argv[2],
    ],
    { stdio: "inherit" }
  );

  const base = path.join(__dirname, "..");
  const generatedDir = path.join(base, "wasm-core", "__generated__");
  await fs.rm(generatedDir, { recursive: true, force: true });
  await fs.mkdir(path.dirname(generatedDir), { recursive: true });
  await fs.rename(tmp, generatedDir);

  const generatedDir2 = path.join(base, "wasm-features", "__generated__");
  await fs.rm(generatedDir2, { recursive: true, force: true });
  await fs.mkdir(generatedDir2, { recursive: true });
  await fs.rename(
    path.join(generatedDir, "features.bin"),
    path.join(generatedDir2, "features.bin")
  );
}

main().catch((e) => {
  console.error(e.stack);
  process.exit(1);
});
