#!/usr/bin/env bash
set -eu

source $HOME/.cargo/env 

NAME='mecab-ipadic.tar.gz'
curl -v -L 'https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7MWVlSDBCSXZMTXM' -o $NAME
tar -zxvf $NAME
rm -rf $NAME

DICT='mecab-ipadic-2.7.0-20070801'
./scripts/build-dict ../$DICT
cd wasm-core
NODE_ENV=production npm run build
