[package]
name = "goya-wasm"
version = "0.1.0"
edition = "2018"
authors = ["Leko <leko.noor@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
morphological_analysis = { path = "../morphological_analysis" }
wasm-bindgen = "0.2.78"
bincode = "1.3"
lazy_static = "1.4"

[unstable]
assoc_char_funcs = true
