[package]
name = "goya"
version = "0.1.0"
edition = "2018"
authors = ["Leko <leko.noor@gmail.com>"]

[dependencies]
morphological_analysis = { path = "../morphological_analysis" }
rustyline = "9.0.0"
indexmap = "1.7"
itertools = "0.10"
bincode = "1.3"
console = "0.14"
clap = "3.0.0-beta.4"
dirs = "4.0"
env_logger = "0.9"
bytesize = {version = "1.1.0", features = ["serde"]}
pprof = { version = "0.4", features = ["flamegraph"] }
rkyv = { git = "https://github.com/rkyv/rkyv", tag = "v0.7.19" }
