[package]
name = "goya-cli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
morphological_analysis = { path = "../morphological_analysis" }
rustyline = "9.0.0"
indexmap = "1.7"
itertools = "0.10"
bincode = "1.3"
indicatif = "0.16"
console = "0.14"
