name: CD

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  crates-io:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: login
          args: ${{ secrets.CRATES_IO_TOKEN }}
      - run: cd goya && cargo publish && sleep 30
      - run: cd ipadic && cargo publish && sleep 30
      - run: cd goya-cli && cargo publish && sleep 30
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: cargo install wasm-pack
      - run: |
          NAME='mecab-ipadic.tar.gz'
          curl -v -L 'https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7MWVlSDBCSXZMTXM' -o $NAME
          tar -zxvf $NAME
          rm -rf $NAME
          ./scripts/build-dict mecab-ipadic-2.7.0-20070801
      - run: ./scripts/build-wasm wasm-core
      - run: cd wasm-core/pkg && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: ./scripts/build-wasm wasm-features
      - run: cd wasm-features/pkg && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
