name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          NAME='mecab-ipadic.tar.gz'
          curl -v -L 'https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7MWVlSDBCSXZMTXM' -o $NAME
          tar -zxvf $NAME
          rm -rf $NAME
          cargo run -p goya-cli --release -- compile mecab-ipadic-2.7.0-20070801
      - run: cargo clippy
      - run: cargo build
      - run: cargo test
  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: benchmarks/package-lock.json
      - run: ./scripts/vercel-install
      - run: |
          NAME='mecab-ipadic.tar.gz'
          curl -v -L 'https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7MWVlSDBCSXZMTXM' -o $NAME
          tar -zxvf $NAME
          rm -rf $NAME
          ./scripts/build-dict mecab-ipadic-2.7.0-20070801
      - run: |
          cd benchmarks
          ./scripts/setup
          npm i
      - run: node goya.js < ita-corpus.txt
      - run: node kuromoji.js < ita-corpus.txt
      - run: node bench.js < ita-corpus.txt
